import {makePortableSnapshot} from './portable-data.js';


import {emptyState,resourceNames,recommendations,simulate,deckBuilder} from './core.js';
import {load,history,saveGoal,backup,scoreHistory,saveLocal,activityHistory,questHistory,exportQuestRecords,restoreQuestRecords} from './db.js';
import {actionWorkspace} from './workspace-ui.js';
import {scoreWorkspace} from './score-ui.js';
import {validatePlan,validateBonus} from './insights.js';
import {generatorPanel,bindGenerator,resetGenerator} from './generator-ui.js';
import {expeditionWorkspace,bindExpedition} from './expedition-ui.js';
import {demoData} from './demo.js';
import {activityRows,activityView} from './activity.js';
import {dropView} from './drop-ui.js';
import {deferredSync} from './deferred-sync.js';
import {questWorkspace,bindQuests} from './quest-ui.js';
const $=s=>document.querySelector(s),esc=v=>String(v??'不明').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=v=>v==null?'—':Number(v).toLocaleString('ja-JP'),time=v=>v?new Date(v).toLocaleString('ja-JP',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'未取得';
const pages=[['activity','≡','行動履歴','ACTIVITY'],['drops','✧','ドロップ履歴','DROPS'],['simulation','⌁','通常海域 編成・装備ジェネレーター','SEA GUIDE'],['expeditions','◷','遠征 編成・装備ジェネレーター','EXPEDITIONS'],['score','↗','戦果','RANK POINTS'],['quests','✓','任務・期限管理','QUESTS']];
let questFacts=[],initialLoaded=false,loading=true,loadError=null;
let activityFacts=[],activityKind='sortie',activityDay='',activityPage=0;
let state=emptyState(),events=[],demo=false,query='',exported=null;
let scoreFacts=[],scoreMonth='all',fleetFilter='all',shipSort='original',shipGroup='class',shipType='all',dropPage=0,dropSize=50,resourceIndex=0,refreshVersion=0;
const routeFocus=()=>location.hash.split('/')[1]||null;
const empty=text=>`<div class="empty"><span class="empty-symbol">⌁</span>${esc(text)}</div>`;
const card=(title,body,extra='')=>`<section class="card"><div class="section-head"><h2>${title}</h2>${extra}</div>${body}</section>`;
const shipName=s=>state.shipMaster[s.masterId]?.name||`艦 #${s.masterId}`;
function resourceCards(all=false){return `<div class="resources">${state.resources.slice(0,all?8:4).map((v,i)=>`<article class="resource" data-resource-index="${i}"><div class="resource-label">${resourceNames[i]}<span>${['◈','▰','⬡','◇'][i%4]}</span></div><strong>${fmt(v)}</strong><small>${v===null?'次回の母港受信で更新':'OBSERVED · 最終取得値'}</small></article>`).join('')}</div>`;}
function chart(index=resourceIndex){const points=events.flatMap(e=>(e.patch?.material||[]).filter(x=>x.id===index+1&&x.value!==null).map(x=>({value:x.value,at:e.at})));if(points.length<2)return empty(`${resourceNames[index]}の推移は2回以上の受信から描画します`);const vals=points.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;const coords=points.map((x,i)=>`${45+i/(points.length-1)*555},${145-(x.value-min)/span*115}`);return `<svg class="chart" viewBox="0 0 620 175" role="img" aria-label="${resourceNames[index]}の取得値の推移"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#167866" stop-opacity=".25"/><stop offset="1" stop-color="#167866" stop-opacity="0"/></linearGradient></defs>${[30,87,145].map(y=>`<line x1="45" y1="${y}" x2="600" y2="${y}" stroke="#cbd5e1" stroke-dasharray="3 6"/>`).join('')}<text x="0" y="33">${Math.round(max/1000)}k</text><text x="0" y="148">${Math.round(min/1000)}k</text><polygon points="45,155 ${coords.join(' ')} 600,155" fill="url(#fill)"/><polyline points="${coords.join(' ')}" fill="none" stroke="#167866" stroke-width="2.5"/></svg><div class="chart-meta"><span>${time(points[0].at)}</span><span>${resourceNames[index]} · ${points.length} 観測点</span><span>${time(points.at(-1).at)}</span></div>`;}
function drops(){return dropView(demo?events:activityFacts,{page:dropPage,size:dropSize,state});}
function goals(){return state.goals.length?state.goals.map(g=>{const v=state.resources[g.resource],pct=v===null?null:Math.min(100,Math.floor(v/g.target*100));return `<div class="goal-item"><div class="goal-title"><span>${esc(g.title)}</span><b>${pct===null?'—':pct+'%'}</b></div><progress max="100" value="${pct??0}" aria-label="${esc(g.title)} 達成率"></progress><div class="goal-meta"><span>${resourceNames[g.resource]} ${fmt(v)} / ${fmt(g.target)}</span><span>優先 ${g.priority}${g.deadline?' · '+esc(g.deadline):''}</span></div></div>`;}).join(''):empty('目標を設定すると、現在資源から進捗を計算します');}
function missions(){const list=(state.fleets||[]).filter(f=>f.mission[0]===1);return list.length?list.map(f=>`<div class="list-row"><span class="number">0${f.id}</span><div class="list-main"><strong>${esc(state.missionMaster[f.mission[1]]?.name||`遠征 #${f.mission[1]}`)}</strong><small>${esc(f.name)}</small></div><span class="list-end">${time(f.mission[2])}<br><small>${f.mission[2]===null?'帰投時刻不明':f.mission[2]<=Date.now()?'帰投時刻経過':`あと ${Math.ceil((f.mission[2]-Date.now())/60000)} 分`}</small></span></div>`).join(''):empty(state.fleets?'取得済み艦隊に遠征中の艦隊はありません':'艦隊の受信を待っています');}
function overview(){return `${resourceCards()}<section class="overview-actions">${card('今できること・確認すること',actionWorkspace(state,true),'<a href="#ships">艦娘・装備から確認 →</a>')}</section><div class="layout"><div class="stack"><section class="hero"><div class="radar" aria-hidden="true"></div><div class="hero-content"><span class="eyebrow">FLEET STATUS</span><h2>艦隊の準備を確認</h2><p>通常海域、遠征、任務の条件確認はシミュレーションから選択できます。</p><a class="link" href="#simulation">シミュレーションを開く →</a></div></section>${card('資源の航跡',chart()+`<div class="mini-stats"><span>高速修復材<b>${fmt(state.resources[5])}</b></span><span>改修資材<b>${fmt(state.resources[7])}</b></span><span>保有艦娘<b>${state.ships?fmt(Object.keys(state.ships).length):'—'} <small>/ ${fmt(state.capacity.ships)}</small></b></span></div>`,'<small>FUEL / OBSERVED</small>')}${card('最近のドロップ',drops(),'<a href="#drops">履歴を見る ↗</a>')}</div><div class="stack">${card('現在の目標',goals(),'<a href="#goals">＋ 追加</a>')}${card('遠征帰投予定',missions(),'<a href="#expeditions">遠征ジェネレーター →</a>')}${card('観測ステータス',`<p class="evidence">母港 ${time(state.portAt)}<br>装備 ${time(state.observed['/api_get_member/slot_item'])}<br>情報は最終受信時点の値です。母港の外で変わった艦娘状態は、次回母港受信で更新されます。</p>`,'<span class="tag">LOCAL</span>')}</div></div>`;}
function table(head,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty('該当する取得データがありません');}
function ships(){return shipWorkspace(state,{query,fleet:fleetFilter,sort:shipSort,group:shipGroup,type:shipType,focus:routeFocus()});}
function goalPage(){return `<div class="layout">${card('目標の進捗',goals())}${card('新しい資源目標',`<form id="goal-form"><label>目標名<input name="title" required maxlength="80" placeholder="次の作戦に向けて燃料を備蓄"></label><div class="forms"><label>対象資源<select name="resource">${resourceNames.map((n,i)=>`<option value="${i}">${n}</option>`).join('')}</select></label><label>目標値<input type="number" name="target" min="1" max="999999999" value="50000" required></label><label>優先度<select name="priority"><option value="1">1 · 高</option><option value="2">2 · 中</option><option value="3">3 · 低</option></select></label><label>期限（任意）<input type="date" name="deadline"></label></div><button class="primary">目標を追加 ＋</button></form>`)}</div>`;}
function simulation(){return generatorPanel(state)+card('周回シミュレーション',`<form id="sim-form"><div class="forms"><label>周回数<input name="runs" type="number" min="0" max="1000000" value="20" required></label><label>1周の燃料消費<input name="cost" type="number" min="0" max="1000000" value="250" required></label><label>1周の取得率（%）<input name="rate" type="number" min="0" max="100" step="any" value="2" required></label></div><button class="primary">シミュレーション実行 →</button></form><div id="sim-result" aria-live="polite"></div><p class="page-note">ユーザー入力に基づく独立試行の仮説計算。遠征・自然回復・修理費を除外。</p>`);}
function content(page){if(['repair','development'].includes(page))return '';if(!demo&&!initialLoaded)return `<section class="card" role="status">${loadError?'読み込みに失敗しました。再読み込みしてお試しください。':'保存データを読み込み中…'}</section>`;if(page==='quests')return questWorkspace(demo?events:questFacts,Date.now(),state);if(page==='activity')return activityView(activityRows(demo?events:activityFacts,state.missionMaster,state.mapMaster),{kind:activityKind,day:activityDay,page:activityPage});if(page==='score')return scoreWorkspace(demo?events:scoreFacts,scoreMonth);switch(page){case 'expeditions':return expeditionWorkspace(state,routeFocus());case 'drops':return drops();case 'simulation':return simulation();default:return simulation();}}
function render(){const page=pages.find(p=>p[0]===location.hash.slice(1).split('/')[0])||pages[0];$('#nav').innerHTML=pages.map(([id,icon,label])=>`<a href="#${id}" ${id===page[0]?'class="active" aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</a>`).join('');$('#breadcrumb').textContent=page[2];$('#connection').textContent=demo?'DEMO · 架空データ':loading?'読み込み中…':loadError?'読み込み失敗':state.portAt?'母港観測済み':'受信待機';$('#demo-banner').hidden=!demo;$('#demo').textContent=demo?'実データに戻る':'デモを見る';$('#page').innerHTML=`<div class="title-row"><div><h1>${page[2]}</h1></div><div class="date">${new Date().toLocaleDateString('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit'})}</div></div>`+content(page[0]);$('#last-update').textContent=`最終受信 ${time(state.updatedAt)} · ${demo?'架空データ':'観測値'}`;bind();}
function download(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bind(){
  if($('#mobile-export'))$('#mobile-export').onclick=()=>{try{if(demo)throw Error('実データに戻してから保存してください。');download(makePortableSnapshot(state),'fleet-compass-pocket.json');$('#notice').textContent='スマホ用データを保存しました。艦隊コンパスポケットの「データ取込」で開いてください。';}catch(error){$('#notice').textContent=error.message;}};document.querySelectorAll('[data-resource-index]').forEach(x=>x.addEventListener('click',()=>{resourceIndex=Number(x.dataset.resourceIndex);render();}));bindWorkspace();$('#search')?.addEventListener('input',e=>{const start=e.target.selectionStart;query=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(start,start);});$('#goal-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target),g={id:crypto.randomUUID(),title:f.get('title').trim(),resource:Number(f.get('resource')),target:Number(f.get('target')),priority:Number(f.get('priority')),deadline:f.get('deadline')||null,status:'active',required_resources:null};if(!g.title||!Number.isInteger(g.target)||g.target<=0)return;try{if(demo){state.goals.push(g);render();}else{await saveGoal(g,emptyState());await refresh(true);}}catch(error){$('#notice').textContent=`目標の保存に失敗しました: ${error.message}`;}});$('#sim-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);try{const r=simulate(state.resources[0],Number(f.get('runs')),Number(f.get('cost')),Number(f.get('rate'))/100);$('#sim-result').innerHTML=`<div class="sim-result">予測燃料残量 <strong>${fmt(r.remaining)}</strong>${r.remaining<0?' <span class="warning">燃料不足</span>':''}<br>1回以上取得する確率 <strong>${(r.probability*100).toFixed(1)}%</strong><br>90%に到達する周回数 ${r.runs90===null?'到達しません':fmt(r.runs90)+' 周'}<br><small>ユーザー入力に基づく仮説計算${r.remaining===null?' · 現在燃料が未取得です':''}</small></div>`;}catch(error){$('#sim-result').textContent=error.message;}});$('#backup')?.addEventListener('click',async()=>{try{download(demo?{version:1,demo:true,state,events}:await backup(),`fleet-compass-${demo?'demo-':''}${new Date().toISOString().slice(0,10)}.json`);}catch(error){$('#notice').textContent=error.message;}});}
async function refresh(force=false){
  if(demo||(!force&&document.activeElement?.closest('form')))return;
  const page=pages.find(p=>p[0]===location.hash.slice(1).split('/')[0])?.[0]||'activity';
  const version=++refreshVersion;loading=true;loadError=null;$('#connection').textContent='読み込み中…';
  try{
    // Read only the current tab's history; unrelated full scans must not delay it.
    const read=page==='activity'||page==='drops'?activityHistory:page==='score'?scoreHistory:page==='quests'?questHistory:null;
    const [nextState,facts]=await Promise.all([load(),read?read():Promise.resolve(null)]);
    if(demo||version!==refreshVersion)return;
    state=nextState||emptyState();
    if(page==='activity'||page==='drops')activityFacts=facts;
    else if(page==='score')scoreFacts=facts;
    else if(page==='quests')questFacts=facts;
    initialLoaded=true;loading=false;render();
  }catch(error){if(demo||version!==refreshVersion)return;loading=false;loadError=error;render();$('#notice').textContent='ローカルDBを読み込めません: '+error.message;}
}
window.addEventListener('hashchange',()=>{query='';if(!demo)initialLoaded=false;render();refresh(true);window.scrollTo({top:0});});$('#demo').addEventListener('click',async()=>{demo=!demo;resetGenerator();if(demo){({state,events}=demoData());render();}else await refresh(true);});$('#export').addEventListener('click',()=>{exported=deckBuilder(state);$('#export-json').value=JSON.stringify(exported.data,null,2);$('#export-warnings').textContent=(demo?'デモの架空IDを含みます。実際の編成として使用しないでください。 ':!state.fleets?'艦隊が未取得です。 ':'')+(exported.warnings.length?`欠落: ${exported.warnings.join('、')}`:'取得済み編成を変換しました。基地航空隊・艦娘の運・装備の現搭載数は出力対象外です。');$('#export-dialog').showModal();});$('#close-dialog').addEventListener('click',()=>$('#export-dialog').close());$('#download-json').addEventListener('click',()=>download(exported.data,`fleet-${demo?'demo-':''}deckbuilder.json`));$('#copy-json').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#export-json').value);$('#export-warnings').textContent='JSONをコピーしました。外部ツール側で貼り付けてください。';}catch{$('#export-json').select();$('#export-warnings').textContent='テキストを選択しました。Ctrl+Cでコピーしてください。';}});
const queueRefresh=deferredSync(()=>refresh(),error=>console.warn('艦隊コンパス表示更新:',error.message),100);
if(globalThis.chrome?.runtime?.id)chrome.runtime.onMessage.addListener(m=>{if(m.type==='updated')queueRefresh();if(m.type==='save-error')$('#notice').textContent='受信データの保存に失敗しました。DevToolsのコンソールを確認してください。';});
// Also observes the integrated YPS collector, which writes in its own DevTools context.
window.addEventListener('focus',()=>refresh());setInterval(()=>{if(!demo&&!document.hidden&&!$('#export-dialog').open&&!document.activeElement?.closest('form')&&document.activeElement?.id!=='search')refresh();},15000);
render();refresh();

function bindWorkspace(){
  bindQuests(()=>demo?render():refresh(true),message=>{$('#notice').textContent=message;},{demo,download,exportRecords:()=>demo?{kind:'fleet-compass-quests',version:1,events:[]}:exportQuestRecords(),restoreRecords:restoreQuestRecords});
  document.querySelectorAll('[data-activity-kind]').forEach(b=>b.addEventListener('click',()=>{activityKind=b.dataset.activityKind;activityPage=0;render();}));
  $('#activity-day')?.addEventListener('change',e=>{activityDay=e.target.value;activityPage=0;render();});
  $('#activity-clear')?.addEventListener('click',()=>{activityDay='';activityPage=0;render();});
  document.querySelectorAll('[data-activity-page]').forEach(b=>b.addEventListener('click',()=>{activityPage=Number(b.dataset.activityPage);render();}));
  bindGenerator(state,download);
  bindExpedition(state);
  $('#fleet-filter')?.addEventListener('change',e=>{fleetFilter=e.target.value;render();});
  $('#ship-sort')?.addEventListener('change',e=>{shipSort=e.target.value;render();});
  $('#ship-group')?.addEventListener('change',e=>{shipGroup=e.target.value;render();});
  document.querySelectorAll('[data-ship-type]').forEach(button=>button.addEventListener('click',()=>{shipType=button.dataset.shipType;render();}));
  $('#drop-size')?.addEventListener('change',e=>{dropSize=Number(e.target.value);dropPage=0;render();});
  $('#score-month')?.addEventListener('change',e=>{scoreMonth=e.target.value;render();});document.querySelectorAll('[data-drop-page]').forEach(b=>b.addEventListener('click',()=>{dropPage=Math.max(0,Number(b.dataset.dropPage));render();}));
  $('#quest-plan-form')?.addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target),plan=validatePlan({questId:Number(e.target.dataset.quest),fleetId:f.get('fleetId')?Number(f.get('fleetId')):null,shipIds:f.getAll('shipIds').map(Number),equipmentIds:f.getAll('equipmentIds').map(Number),note:f.get('note').trim()});if(demo){state.questPlans||={};state.questPlans[plan.questId]=plan;render();}else{await saveLocal('quest-plan',plan,emptyState());await refresh(true);}$('#notice').textContent='編成計画を保存しました。艦娘・装備側にも関連任務が表示されます。';}catch(error){$('#notice').textContent=error.message;}});
  $('#score-bonus-form')?.addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const f=new FormData(e.target),bonus=validateBonus({value:Number(f.get('value')),month:f.get('month'),kind:f.get('kind'),note:f.get('note').trim()});if(demo){events.push({id:crypto.randomUUID(),at:new Date().toISOString(),path:'local/score-bonus',changes:[],bonus});render();}else{await saveLocal('score-bonus',bonus,emptyState());await refresh(true);}$('#notice').textContent='手動戦果を追記しました。';}catch(error){$('#notice').textContent=error.message;button.disabled=false;}});
  $('#score-calc-form')?.addEventListener('submit',e=>{e.preventDefault();const xp=Number(new FormData(e.target).get('xp'));if(Number.isSafeInteger(xp)&&xp>=0)$('#score-calc-result').textContent=xp.toLocaleString()+' EXP = '+(xp*7/10000).toFixed(3)+' 戦果';});
}

