import {fleetOf,shipActions,equipmentOf} from './insights.js';
import {equipmentPlanFor} from './generator.js';
const e=v=>String(v??'不明').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=v=>v==null?'—':Number(v).toLocaleString('ja-JP');
const typeNames={1:'海防艦',2:'駆逐艦',3:'軽巡洋艦',4:'重雷装巡洋艦',5:'重巡洋艦',6:'航空巡洋艦',7:'軽空母',8:'巡洋戦艦',9:'戦艦',10:'航空戦艦',11:'正規空母',13:'潜水艦',14:'潜水空母',16:'水上機母艦',18:'装甲空母',19:'工作艦',20:'潜水母艦',21:'練習巡洋艦',22:'補給艦'};
const areaNames={1:'鎮守府海域',2:'南西諸島海域',3:'北方海域',4:'西方海域',5:'南方海域',6:'中部海域',7:'南西海域'};
export const EXPEDITION_SOURCE={url:'https://wikiwiki.jp/kancolle/遠征',retrievedAt:'2026-09-08',scope:'海域名・艦種略記・遠征成功条件の表示根拠'};
const missionList=state=>Object.values(state.missionMaster||{}).sort((a,b)=>(a.mapArea??999)-(b.mapArea??999)||(a.id??0)-(b.id??0));
const mapName=m=>m?`${areaNames[m.mapArea]||`第${m.mapArea}海域`} (${m.mapArea??'?'}-X)`: '海域未取得';
const EXPEDITION_REFERENCE={
  1:{min:2,types:'艦種自由'},2:{min:4,types:'艦種自由'},3:{min:3,types:'艦種自由'},4:{min:3,types:'軽巡1・駆逐/海防2'},5:{min:4,types:'軽巡1・駆逐/海防2・他1'},6:{min:4,types:'艦種自由'},7:{min:6,types:'艦種自由'},8:{min:6,types:'艦種自由'},
  9:{min:4,types:'軽巡1・駆逐/海防2・他1'},10:{min:3,types:'軽巡2・他1'},11:{min:4,types:'駆逐/海防2・他2'},12:{min:4,types:'駆逐/海防2・他2'},13:{min:6,types:'軽巡1・駆逐4・他1'},14:{min:6,types:'軽巡1・駆逐3・他2'},15:{min:6,types:'空母/水母/護衛空母2・駆逐2・他2'},16:{min:6,types:'軽巡1・駆逐2・他3'},
  17:{min:6,types:'軽巡1・駆逐3・他2'},18:{min:6,types:'空母/水母/護衛空母3・駆逐2・他1'},19:{min:6,types:'航空戦艦2・駆逐2・他2'},20:{min:2,types:'潜水艦1・軽巡1'},21:{min:5,types:'軽巡1・駆逐4',drums:3,drumShips:3},22:{min:6,types:'重巡1・軽巡1・駆逐2・他2'},23:{min:6,types:'航空戦艦2・駆逐2・他2'},24:{min:6,types:'軽巡1（旗艦）・駆逐/海防4・他1',drums:4},
  25:{min:4,types:'重巡2・駆逐2'},26:{min:4,types:'空母1・軽巡1・駆逐2'},27:{min:2,types:'潜水艦2'},28:{min:3,types:'潜水艦3'},29:{min:3,types:'潜水艦3'},30:{min:4,types:'潜水艦4'},31:{min:4,types:'潜水艦4'},32:{min:3,types:'練巡1・駆逐2'},35:{min:6,types:'空母2・重巡1・駆逐1・他2'},36:{min:6,types:'水母2・軽巡1・駆逐1・他2'},37:{min:6,types:'軽巡1・駆逐5',drums:4,drumShips:3},38:{min:6,types:'駆逐5・他1',drums:8,drumShips:4},39:{min:5,types:'潜水母艦1・潜水艦4'},40:{min:6,types:'軽巡1・水母2・駆逐2・他1',drums:4},41:{min:3,types:'駆逐/海防3'},42:{min:4,types:'軽巡1・駆逐2・他1'},43:{min:6,types:'護衛空母/軽空母1（旗艦）・駆逐/海防2・他3'},44:{min:6,types:'空母1・水母1・軽巡1・駆逐/海防2・他1',drums:8},45:{min:5,types:'軽空母1・駆逐/海防4'},46:{min:5,types:'重巡2・軽巡1・駆逐2'}
};
const conditionSummary=m=>{const ref=EXPEDITION_REFERENCE[m?.id];const d=String(m?.details||'');const types=['駆逐艦','軽巡洋艦','重巡洋艦','戦艦','空母','軽空母','水母','海防艦','潜水艦','揚陸艦','補給艦'].filter(x=>d.includes(x));const drum=d.match(/ドラム缶[^0-9]*(\d+)\s*個/);return {min:ref?.min??m?.deckNum??null,types:ref?.types?[ref.types]:[...new Set(types)],drums:ref?.drums??(drum?Number(drum[1]):null),drumShips:ref?.drumShips??null};};
const equipmentPlan=(state,fleet,mission)=>{if(!fleet)return '<p class="compact-empty">艦隊を選択すると、遠征用の装備組み合わせを表示します。</p>';const ships=(fleet.shipIds||[]).map(id=>state.ships?.[id]).filter(Boolean);const asw=(mission.details||'').includes('対潜');const rows=equipmentPlanFor(state,ships,{policy:asw?'対潜優先':'通常',threat:asw?'対潜':'通常'});return rows.map((r,i)=>`<div class="plan-ship"><b>${i+1}. ${e(state.shipMaster[ships.find(s=>s.id===r.shipId)?.masterId]?.name||`艦 #${r.shipId}`)}</b><div class="chip-list">${r.items.map(x=>`<a class="chip equipment-chip" href="#equipment/${x.id}">${e(x.slot)} ${e(x.name)}${x.stars!=null?` ★${x.stars}`:''}</a>`).join('')||'<span class="warning">候補なし</span>'}</div>${r.gaps.length?`<small class="warning">${r.gaps.map(e).join(' / ')}</small>`:''}</div>`).join('')||'<p class="compact-empty">装備または艦娘の受信データが不足しています。</p>';};
function shipCounts(state,ids){const counts={};for(const id of ids){const s=state.ships?.[id],t=state.shipMaster[s?.masterId]?.type;if(t)counts[t]=(counts[t]||0)+1;}return counts;}
function equipmentSummary(state,ids){const items=ids.flatMap(id=>{const s=state.ships?.[id];return s?[...s.slots,s.extraSlot].filter(x=>x>0).map(x=>state.equipment?.[x]):[]}).filter(Boolean);const names=items.map(x=>state.equipmentMaster[x.masterId]?.name||`装備 #${x.masterId}`);const categories=items.map(x=>state.equipmentMaster[x.masterId]?.category).filter(Number.isInteger);const drums=categories.filter(x=>x===30||x===24).length;const daihatsu=categories.filter(x=>x===68||x===46||x===29).length;return {names,categories,drums,daihatsu};}
function compareFleet(state,fleet,mission){const ids=fleet?.shipIds||[],ships=ids.map(id=>state.ships?.[id]).filter(Boolean),counts=shipCounts(state,ids),eq=equipmentSummary(state,ids),issues=[];if(mission.deckNum&&ids.length<mission.deckNum)issues.push(`必要艦数 ${mission.deckNum}隻に対し${ids.length}隻`);if(!ships.length)issues.push('艦隊未取得');if(ships.some(s=>s.hp!=null&&s.maxHp>0&&s.hp/s.maxHp<=.25))issues.push('大破艦あり');if(eq.drums)issues.push(`ドラム缶 ${eq.drums}個を確認`);if(eq.daihatsu)issues.push(`大発系 ${eq.daihatsu}個を確認`);return {ids,ships,counts,eq,issues};}
function fleetOption(state){return (state.fleets||[]).map(f=>`<option value="${f.id}">${e(f.name)}</option>`).join('');}
export function expeditionWorkspace(state,focus){const missions=missionList(state),selected=missions.find(m=>m.id===Number(focus))||missions[0];if(!selected)return '<p class="compact-empty">遠征マスターの受信を待っています。</p>';const active=(state.fleets||[]).find(f=>f.mission?.[0]===1),comparison=compareFleet(state,active,selected),c=conditionSummary(selected);return `<div class="expedition-lab"><section class="card compact-card"><div class="section-head"><div><span class="eyebrow">EXPEDITION LAB</span><h2>遠征ジェネレーター</h2></div><span class="tag">遠征 → 現在艦隊を照合</span></div><p class="page-note">公開資料の値は同梱した参考値です。実行時は外部通信しません。</p><label>海域・遠征<select id="expedition-select">${missions.map(m=>`<option value="${m.id}" ${m.id===selected.id?'selected':''}>${e(mapName(m))} · ${e(m.dispNo||`遠征 #${m.id}`)} ${e(m.name)}</option>`).join('')}</select></label><div class="expedition-meta"><span>所要時間 <b>${selected.durationMin==null?'不明':`${Math.floor(selected.durationMin/60)}時間${selected.durationMin%60}分`}</b></span><span>必要艦数・条件 <b>${c.min??'不明'}隻</b><small>${c.types.length?c.types.join('・'):'艦種条件は説明文未取得'}</small></span><span>大成功条件 <b>${c.drums!=null?`ドラム缶${c.drums}個`: '任務別条件を確認'}</b><small>キラ・旗艦Lvは参考値を表示</small></span></div><div class="expedition-condition"><b>成功条件</b><p>${selected.details?e(selected.details).replace(/&lt;br\s*\/?&gt;/gi,'<br>'):'説明文は未取得です。ゲームから遠征マスターを受信すると表示します。'}</p><p class="condition-summary">必要艦種・組み合わせ：${c.types.length?c.types.join('・'):'未取得'}${c.drums!=null?` ／ 必要ドラム缶：${c.drums}個`:' ／ 装備条件は未取得'}</p></div><div class="forms"><label>照合する艦隊<select id="expedition-fleet"><option value="">現在の遠征艦隊</option>${fleetOption(state)}</select></label><div class="expedition-check" id="expedition-check">${renderCheck(state,active,selected)}</div><section class="expedition-plan"><h3>遠征用の装備組み合わせ</h3><p class="page-note">ドラム缶・大発・対潜装備を、受信済みの保有装備から候補提示します。</p>${equipmentPlan(state,active,selected)}</section></div></section><section class="card compact-card"><h3>必要条件と判定範囲</h3><div class="requirement-grid"><div><b>艦種・隻数</b><p>${c.min??'不明'}隻 / ${c.types.length?c.types.join('・'):'条件未取得'}</p></div><div><b>旗艦レベル</b><p>遠征マスターまたは同梱参考値に記載がある場合のみ表示します。</p></div><div><b>大成功</b><p>キラ・旗艦Lv型の条件を参考値として表示します。確率は断定しません。</p></div><div><b>注意事項</b><p>火力・対空・対潜・索敵や装備制約が不足すると失敗する場合があります。</p></div></div></section></div>`;}
function renderCheck(state,fleet,mission){if(!fleet)return '<p class="compact-empty">照合する艦隊を選択してください。艦隊の現在メンバー、Lv、Cond、装備を使って不足を表示します。</p>';const c=compareFleet(state,fleet,mission),names=c.ships.map(s=>state.shipMaster[s.masterId]?.name||`艦 #${s.masterId}`).join('・'),drumShips=c.ships.filter(s=>equipmentOf(state,s).some(x=>/ドラム缶/.test(x.name||''))).length;return `<p><b>${e(fleet.name)}</b> · ${c.ships.length}隻<br><small>${e(names||'艦娘未取得')}</small></p><div class="chip-list">${Object.entries(c.counts).map(([t,count])=>`<span class="chip">${e(typeNames[t]||`艦種 #${t}`)} ${count}</span>`).join('')||'<span class="muted">艦種不明</span>'}${c.eq.drums?`<span class="chip equipment-chip">ドラム缶 ${c.eq.drums}個（${drumShips}隻に搭載）</span>`:'<span class="chip warning">ドラム缶 0個（搭載艦 0隻）</span>'}${c.eq.daihatsu?`<span class="chip equipment-chip">大発系 ${c.eq.daihatsu}個（現在艦隊）</span>`:''}</div>${c.issues.length?`<p class="warning">${c.issues.map(e).join('<br>')}</p>`:'<p class="success">観測できる範囲では大きな不足なし。最低Lv・大成功条件は未取得です。</p>'}`;}
export function bindExpedition(state){document.querySelector('#expedition-select')?.addEventListener('change',ev=>{location.hash=`#expeditions/${ev.target.value}`;});document.querySelector('#expedition-fleet')?.addEventListener('change',ev=>{const root=document.querySelector('#expedition-check');const mission=missionList(state).find(m=>m.id===Number(document.querySelector('#expedition-select').value));const fleet=(state.fleets||[]).find(f=>f.id===Number(ev.target.value))||((state.fleets||[]).find(f=>f.mission?.[0]===1));root.innerHTML=renderCheck(state,fleet,mission);});}
