import {generateFleet,availableMaps,policyOptions,candidateDeck,profileFor} from './generator.js';
import {escape as e} from './workspace-ui.js';
let formState={area:'1',mapId:'1-5',templateId:'',mode:'auto',policy:'通常',selectedIds:[],allowTransfers:false},result=null,resultState=null;
const roles={gun:'主砲',torpedo:'魚雷',fighter:'艦戦',attack:'攻撃機',torpedoBomber:'艦攻',diveBomber:'艦爆',seaplane:'水上機',charge:'爆雷',scout:'偵察機',radar:'電探',sonar:'ソナー',depth:'爆雷系',aa:'機銃',保持:'保持'};
const areaNames={1:'鎮守府海域',2:'南西諸島海域',3:'北方海域',4:'西方海域',5:'南方海域',6:'中部海域',7:'南西海域'};
export const profileNote=p=>[p.templates?.map(t=>t.name+(t.referenceOnly?'（参考のみ）':'')).join(' ／ '),p.requirements||p.note].filter(Boolean).join('\n');
const mapOptions=s=>availableMaps(s).filter(m=>m.area===formState.area).map(m=>`<option value="${e(m.id)}" ${m.id===formState.mapId?'selected':''}>${e(m.name)}</option>`).join('');
export const templateOptions=p=>'<option value="">異なる編成を比較（最大3案）</option>'+p.templates.map(t=>`<option value="${e(t.id)}" ${t.id===formState.templateId?'selected':''}>${e(t.name)}${t.referenceOnly?'（参考のみ）':''}</option>`).join('');
export function generatorPanel(state){
  const maps=availableMaps(state);if(!maps.some(x=>x.id===formState.mapId)){formState.area='1';formState.mapId='1-5';}
  return `<section class="card compact-card"><div class="section-head"><div><span class="eyebrow">FLEET & EQUIPMENT LAB</span><h2>艦隊・装備ジェネレーター</h2></div><span class="tag">目的別に手持ち装備を自動配分</span></div><form id="generator-form"><div class="generator-controls"><label>海域<select name="area" id="generator-area">${[...new Set(maps.map(m=>m.area))].map(a=>`<option value="${e(a)}" ${a===formState.area?'selected':''}>${a==='custom'?'任意海域':`${e(areaNames[a]||`第${a}海域`)} (${e(a)}-X)`}</option>`).join('')}</select></label><label>マップ<select name="mapId" id="generator-map">${mapOptions(state)}</select></label><label>編成パターン<select name="templateId" id="generator-template">${templateOptions(profileFor(state,formState.mapId))}</select></label><label>編成モード<select name="mode"><option value="auto" ${formState.mode==='auto'?'selected':''}>自動で艦娘と装備を選ぶ</option><option value="manual" ${formState.mode==='manual'?'selected':''}>選択艦だけ固定・装備を提案</option><option value="hybrid" ${formState.mode==='hybrid'?'selected':''}>選択艦を固定・残りを補完</option></select></label><label>装備方針<select name="policy">${policyOptions().map(p=>`<option ${p===formState.policy?'selected':''}>${e(p)}</option>`).join('')}</select></label></div><div class="generator-selection"><label>固定する艦娘（手動・補完モード、Ctrlで複数選択）<select name="selectedIds" multiple size="5">${Object.values(state.ships||{}).map(s=>`<option value="${s.id}" ${formState.selectedIds.includes(s.id)?'selected':''}>#${s.id} ${e(state.shipMaster[s.masterId]?.name||`艦 #${s.masterId}`)} Lv${s.level??'?'} / HP${s.hp??'?'}</option>`).join('')}</select></label><div><p id="generator-profile-note" class="page-note" style="white-space:pre-line">${e(profileNote(profileFor(state,formState.mapId)))}</p><label class="inline-check"><input type="checkbox" name="allowTransfers" ${formState.allowTransfers?'checked':''}>候補外の待機艦から装備の移動も提案する</label><p class="page-note">既定は未装備品と候補艦の装備を使用。増設枠は現装備を保持します。遠征・入渠中、大破、耐久不明の艦は除外します。</p><button class="primary">編成・装備候補を生成 →</button></div></div></form><div id="generator-error" role="status"></div></section><div id="generator-result">${result?renderResults(result,state):'<p class="compact-empty">海域・方針を選ぶと、保有装備から役割別に自動配分し、艦種構成が異なる候補を最大3案比較できます。4案目以降は「編成パターン」で選べます。</p>'}</div>`;
}
function renderResults(r,state){return `<div class="generator-summary"><strong>${e(r.profile.name)} / ${e(r.policy)}</strong><span>${r.candidates.length} 案</span></div>${resultState&&resultState.updatedAt!==state.updatedAt?'<p class="warning">生成後に新しい観測があります。現在状態で再生成してください。</p>':''}${r.warnings.map(w=>`<p class="warning">${e(w)}</p>`).join('')}${r.candidates.map((c,index)=>`<section class="card compact-card generated-candidate"><div class="section-head"><h2>候補 ${index+1} · ${e(c.variant||c.template)} · ${e(c.template)}</h2><button data-candidate-export="${index}">候補JSONを保存 ↓</button></div><p class="page-note">${e(c.reason)}</p>${c.notes?`<p class="warning">${e(c.notes)}</p>`:''}<div class="table-wrap"><table class="generator-table"><thead><tr><th>順 / 艦娘</th><th>候補装備（保有ID単位）</th><th>装備の移動</th></tr></thead><tbody>${c.ships.map((s,i)=>{const row=c.equipment.find(x=>x.shipId===s.id);return `<tr><td><a class="ship-link" href="#ships/${s.id}">${i+1}. ${e(s.name)}</a><small>Lv${s.level??'?'} / HP${s.hp}/${s.maxHp}</small></td><td><div class="chip-list">${row.items.map(x=>`<a class="chip equipment-chip" href="#equipment/${x.id}" title="保有 #${x.id} / ${e(x.basis)}">${x.slot==='ix'?'増設':x.slot.slice(1)} ${e(x.name)}${x.stars!=null?' ★'+x.stars:''}${x.proficiency>0?' ▰'+x.proficiency:''}</a>`).join('')||'<span class="warning">装備候補なし</span>'}</div><small>優先役割: ${row.roles.map(x=>roles[x]||x).join(' → ')}</small></td><td>${row.items.filter(x=>x.from!==s.id).map(x=>`<small>#${x.id}: ${x.from?'艦 #'+x.from+'から':'未装備品から'}</small>`).join('')||'<small>現在装備を使用</small>'}</td></tr>`;}).join('')}</tbody></table></div>${c.gaps.length?`<details><summary>装備不足・未判定 ${c.gaps.length} 件</summary><p class="page-note">${c.gaps.map(g=>e(g.replace(/torpedoBomber|diveBomber|seaplane|charge|sonar|depth|gun|fighter|attack|radar|scout|torpedo|aa/g,k=>roles[k]))).join('<br>')}</p></details>`:''}</section>`).join('')}<section class="card compact-card"><h3>自動組み合わせの根拠と未判定条件</h3><p class="page-note">${r.limitations.map(e).join('<br>')}</p>${r.profile.source?`<a class="chip" href="${e(r.profile.source)}" target="_blank" rel="noreferrer">編成例の出典 ↗</a><small> 確認 ${e(r.profile.retrieved_at)} / 有効期限 ${e(r.profile.valid_until)}</small>`:'<small>海域別の攻略条件は未登録</small>'}<p class="page-note">艦種別の役割、Lv×0.45、Cond×0.15、耐久率×12などで候補を比較。装備は艦別の搭載可否を優先し、艦攻は雷装・艦爆は爆装・艦戦は対空を優先して、保有数・装備可否・現在の搭載位置を照合します。用途が違う現装備で空欄を埋めず、不足として表示します。必須装備や任務の指定艦は、別途条件を満たすよう調整してください。</p></section>`;}
export function bindGenerator(state,download){
  const form=document.querySelector('#generator-form');if(!form)return;
  function remember(){const f=new FormData(form);formState={area:f.get('area'),mapId:f.get('mapId'),templateId:f.get('templateId')||'',mode:f.get('mode'),policy:f.get('policy'),selectedIds:f.getAll('selectedIds').map(Number),allowTransfers:f.has('allowTransfers')};}
  form.addEventListener('change',event=>{remember();if(event.target.name==='area'){const choices=availableMaps(state).filter(m=>m.area===formState.area);formState.mapId=choices[0].id;document.querySelector('#generator-map').innerHTML=mapOptions(state);}if(['area','mapId'].includes(event.target.name)){formState.templateId='';document.querySelector('#generator-template').innerHTML=templateOptions(profileFor(state,formState.mapId));}document.querySelector('#generator-profile-note').textContent=profileNote(profileFor(state,formState.mapId));document.querySelector('#generator-error').textContent='条件を変更しました。候補を再生成してください。';});
  const exports=()=>document.querySelectorAll('[data-candidate-export]').forEach(button=>button.addEventListener('click',()=>{const c=result?.candidates[Number(button.dataset.candidateExport)];if(c)download(candidateDeck(c,resultState),`fleet-candidate-${result.profile.id}-${Number(button.dataset.candidateExport)+1}.json`);}));
  form.addEventListener('submit',event=>{event.preventDefault();remember();try{result=generateFleet(state,formState);resultState=structuredClone(state);document.querySelector('#generator-result').innerHTML=renderResults(result,state);document.querySelector('#generator-error').textContent='';exports();}catch(error){result=null;resultState=null;document.querySelector('#generator-result').innerHTML='';document.querySelector('#generator-error').textContent=error.message;}});exports();
}
export function resetGenerator(){result=null;resultState=null;}
