import {questModel,periodLabels} from './quest-manager.js';
import {questCatalog} from './quest-catalog.js';
import {saveQuestCorrection} from './db.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dt=t=>t?new Date(t).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const statuses={unknown:'未確認',unaccepted:'未受注',active:'受注中',achieved:'達成・報酬待ち',complete:'完了',locked:'未出現'};
let filters={period:'regular',status:'all',text:''};
const openKeys=new Set();
const progress=r=>r.status==='complete'||r.status==='achieved'?'達成':(r.progress===2?'80%以上':r.progress===1?'50%以上':r.localProgress?'':'回数未確認')+(r.localProgress?`<small>${r.localProgress.count}/${r.localProgress.max}（PC記録）</small>`:'');
export function questWorkspace(events,now=Date.now(),state={}){
 const model=questModel(events,now),rows=model.rows.filter(r=>(filters.period==='all'||filters.period==='regular'&&r.period!=='once'||filters.period===r.period)&&(filters.status==='all'||filters.status==='unfinished'&&!['complete'].includes(r.status)||filters.status===r.status)&&(!filters.text||r.title.includes(filters.text))).sort((a,b)=>(a.status==='complete')-(b.status==='complete')||(a.periodInfo.end??Infinity)-(b.periodInfo.end??Infinity)||a.title.localeCompare(b.title,'ja'));
 return `<section class="card quest-manager"><div class="section-head"><h2>任務・期限管理</h2><span>${rows.length}件</span></div><div class="toolbar"><label>周期<select id="quest-period">${Object.entries({regular:'定期任務',all:'すべて',...periodLabels}).map(([k,v])=>`<option value="${k}" ${filters.period===k?'selected':''}>${v}</option>`).join('')}</select></label><label>状態<select id="quest-status">${Object.entries({all:'すべて',unfinished:'未完了',...statuses}).map(([k,v])=>`<option value="${k}" ${filters.status===k?'selected':''}>${v}</option>`).join('')}</select></label><form id="quest-search-form"><label>任務名<input name="text" value="${esc(filters.text)}" placeholder="任務名で検索"></label><button>検索</button></form></div>
 <p class="page-note">任務一覧を通常操作で開くと、受信した任務から照合します。更新時刻は日本時間です。<br>スマホ利用中の行動は復元せず、今期の状態・前回記録・手動補正を区別します。</p>
 ${monthlyMissions(state,now,model.session)}<div class="table-wrap"><table><thead><tr><th>周期</th><th>任務・詳細</th><th>状態</th><th>進捗</th><th>次回更新 / 残り</th></tr></thead><tbody>${rows.map(r=>{
 const senka=model.senka?.quests?.find(q=>q.title===r.title),senkaCurrent=senka&&+new Date(model.senka.at)>=(r.periodInfo.start||0);
 return `<tr><td>${esc(periodLabels[r.period])}${r.period==='year'&&r.month?`・${r.month}月`:''}</td><td><details data-quest-key="${esc(r.id)}"><summary>${esc(r.title)}</summary><p>${esc(r.reason)}${!r.fresh&&r.raw?' / 前回記録・再確認待ち':''}<br>最終確認 ${dt(r.observedAt)}</p>${r.description?`<p>${esc(r.description).replace(/&lt;br\s*\/?&gt;/gi,'<br>')}</p>`:''}
 ${r.parents?.length?`<p>前提：${r.parents.map(k=>esc(questCatalog.quests.find(c=>c.key===k)?.title||k)).join(' / ')}${r.verified?'':'（条件確認中・自動判定対象外）'}</p>`:''}
 ${r.source?`<p><a href="${esc(r.source)}" target="_blank" rel="noreferrer">Wikiの根拠</a> ／ 確認 ${esc(questCatalog.checkedAt.slice(0,10))}</p>`:''}
 ${senkaCurrent?`<div class="quest-senka"><p>${esc(senka.line)}</p>${senka.maps.map(m=>`<span>${esc(m.map)} ${m.count}/${m.max}${m.manual?'（手動）':''}　</span>`).join('')}<button data-senka-edit="${esc(senka.id)}">海域回数を補正</button></div>`:''}
 ${r.periodInfo.key!=='unknown'?`<form class="quest-correction" data-id="${esc(r.id)}" data-period="${esc(r.periodInfo.key)}"><label>今期の状態を補正<select name="status">${Object.entries({'':'補正を解除',unaccepted:'未受注',active:'受注中',achieved:'達成・報酬待ち',complete:'完了（スマホ等で受取済み）'}).map(([k,v])=>`<option value="${k}" ${(r.manual?.status||'')===k?'selected':''}>${v}</option>`).join('')}</select></label><label>メモ<input name="note" maxlength="300" value="${esc(r.manual?.note||'')}"></label><button>補正を保存</button></form>`:''}
 <details><summary>受信・補正の履歴（${r.history.length}件）</summary>${r.history.length?r.history.slice().reverse().map(h=>`<div>${dt(h.at)}　${esc(h.kind)}　${esc(({1:'未受注',2:'受注中',3:'達成',4:'完了'})[h.state]||statuses[h.state]||'')} ${esc(h.note||'')}</div>`).join(''):'履歴なし'}</details></details></td>
 <td>${esc(statuses[r.status])}${!r.fresh&&r.raw&&!['complete'].includes(r.status)?'<small>再確認待ち</small>':''}${r.manual?.status?'<small>手動補正あり</small>':''}</td><td>${progress(r)}</td><td>${dt(r.periodInfo.end)}${r.periodInfo.end?`<small>残り ${Math.max(0,Math.ceil((r.periodInfo.end-now)/86400000))}日</small>`:''}</td></tr>`;}).join('')}</tbody></table></div><div class="toolbar"><button id="quest-backup">任務記録を保存</button><label>任務記録を復元<input id="quest-restore" type="file" accept="application/json,.json"></label></div><p class="page-note">記録はこのPC内に保存します。復元は既存記録を残して追加し、重複は取り込みません。</p></section>`;
}
export function monthlyMissionPeriod(now){const d=new Date(now-3*3600000),y=d.getUTCFullYear(),m=d.getUTCMonth()-(d.getUTCDate()<15?1:0);return {start:Date.UTC(y,m,15,3),end:Date.UTC(y,m+1,15,3)};}
function monthlyMissions(state,now,session){const period=monthlyMissionPeriod(now),received=state.missionStatus,current=received&&Date.parse(received.at)>=period.start&&(!received.deadline||now<received.deadline),fresh=current&&Date.parse(received.at)>=session;
 const masters=Object.values(state.missionMaster||{}).filter(m=>m.resetType>0);
 return `<details class="monthly-missions"><summary>マンスリー遠征　次回更新 ${dt(current&&received.deadline?received.deadline:period.end)}（毎月15日12時）</summary><p>遠征メニュー受信時点の情報です。${fresh?'今回確認済み':'再確認待ち'}</p>${masters.length?`<table><thead><tr><th>遠征</th><th>今期の状態</th></tr></thead><tbody>${masters.map(m=>{const entry=current?received.items.find(x=>x.id===m.id):null,running=Date.parse(state.observed?.['/api_get_member/deck']||state.portAt||0)>=session&&(state.fleets||[]).some(f=>f.mission?.[0]===1&&f.mission?.[1]===m.id);return `<tr><td>${esc(m.dispNo)} ${esc(m.name)}</td><td>${running?'遠征中':!current?'更新後・確認待ち':entry?.state===2?'クリア済み':entry?.state===1?'未クリア':!entry?'未出現':'未確認'}${!fresh&&current?'（前回記録）':''}</td></tr>`;}).join('')}</tbody></table>`:'<p>遠征マスター未取得。通常起動後に遠征メニューを開くと照合します。</p>'}</details>`;
}
async function senkaRequest(body){if(!globalThis.chrome?.runtime?.id)throw Error('F12を開いた拡張機能で利用してください');const r=await chrome.runtime.sendMessage({type:'yps-senka-local',...body});if(!r?.ok)throw Error(r?.error||'F12を開き、母港を受信してからお試しください');return r;}
export function bindQuests(refresh,notice,{demo=false,download,exportRecords,restoreRecords}={}){
 document.querySelectorAll('[data-quest-key]').forEach(el=>{el.open=openKeys.has(el.dataset.questKey);el.addEventListener('toggle',()=>{if(!el.isConnected)return;if(el.open)openKeys.add(el.dataset.questKey);else openKeys.delete(el.dataset.questKey);});});
 for(const [id,key] of [['quest-period','period'],['quest-status','status']])document.getElementById(id)?.addEventListener('change',e=>{filters[key]=e.target.value;refresh();});
 document.getElementById('quest-search-form')?.addEventListener('submit',e=>{e.preventDefault();filters.text=new FormData(e.target).get('text');refresh();});
 document.querySelectorAll('.quest-correction').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();if(demo){notice('デモでは補正を保存しません');return;}try{const f=new FormData(form);await saveQuestCorrection({id:form.dataset.id.startsWith('wiki:')?form.dataset.id:Number(form.dataset.id),period:form.dataset.period,status:f.get('status')||null,note:f.get('note')});notice('今期の補正を保存しました');await refresh();}catch(error){notice(error.message);}}));
 document.querySelectorAll('[data-senka-edit]').forEach(button=>button.addEventListener('click',async()=>{if(demo){notice('デモでは補正を保存しません');return;}try{
   const snap=await senkaRequest({op:'get'}),quest=snap.quests.find(q=>q.id===button.dataset.senkaEdit);if(!snap.ready||!quest)throw Error('母港へ戻ってから補正してください');
   const dialog=document.createElement('dialog');dialog.innerHTML=`<h2>${esc(quest.title)}</h2><p>未記録分を含めた現在の合計回数です。右側の戦果メモと共通です。</p><div class="senka-edit-status" role="status"></div>${quest.maps.map((m,i)=>`<form data-map-index="${i}"><label>${esc(m.map)}<input type="number" min="0" max="${m.max}" value="${m.count}" name="count" required></label><button>保存</button><button type="button" data-reset>補正解除</button></form>`).join('')}<button data-close>閉じる</button>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.onclose=()=>dialog.remove();
   dialog.querySelectorAll('form').forEach(form=>{async function update(count){try{await senkaRequest({op:'set',token:snap.token,quest:quest.id,map:quest.maps[Number(form.dataset.mapIndex)].map,count});dialog.querySelector('.senka-edit-status').textContent='保存しました';await refresh();}catch(error){dialog.querySelector('.senka-edit-status').textContent=error.message;}}form.onsubmit=e=>{e.preventDefault();update(Number(new FormData(form).get('count')));};form.querySelector('[data-reset]').onclick=()=>update(null);});
 }catch(error){notice(error.message);}}));
 document.getElementById('quest-backup')?.addEventListener('click',async()=>{try{download(await exportRecords(),'fleet-compass-quests.json');}catch(e){notice(e.message);}});
 document.getElementById('quest-restore')?.addEventListener('change',async e=>{if(demo){notice('デモでは復元しません');return;}try{const f=e.target.files[0];if(!f)return;if(f.size>20000000)throw Error('20MB以下の任務記録を指定してください');const n=await restoreRecords(JSON.parse(await f.text()));notice(`${n}件の記録を追加しました`);await refresh();}catch(error){notice(error.message);}});
}
