import {scoreSeries,operationMonth} from './insights.js';
import {escape as e} from './workspace-ui.js';
const date=at=>new Date(at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
const panel=(title,body)=>`<section class="card compact-card"><div class="section-head"><h2>${title}</h2></div>${body}</section>`;
export function scoreWorkspace(records,month='all'){
  const s=scoreSeries(records,month),months=[...new Set(records.map(x=>x.bonus?.month||operationMonth(x.at)))].sort().reverse();
  const rows=s.rows,first=rows[0],last=rows.at(-1),min=rows.length?Math.min(0,...rows.map(x=>x.total)):0,max=rows.length?Math.max(1,...rows.map(x=>x.total)):1;
  const span=last?Math.max(1,Date.parse(last.at)-Date.parse(first.at)):1;
  const points=rows.map(r=>({...r,x:55+(Date.parse(r.at)-Date.parse(first.at))/span*735,y:185-(r.total-min)/(max-min)*150}));
  const plot=points.length?`<svg viewBox="0 0 820 225" class="score-chart" role="img" aria-label="観測開始後の累積戦果 ${s.total.toFixed(3)}。通常戦果と手動加算の合計"><line x1="55" y1="185" x2="790" y2="185" stroke="#cbd5e1"/><line x1="55" y1="35" x2="790" y2="35" stroke="#cbd5e1" stroke-dasharray="4 5"/><text x="0" y="40">${max.toFixed(1)}</text><text x="0" y="188">${min.toFixed(1)}</text><polyline points="${points.map(p=>`${p.x},${p.y}`).join(' ')}" fill="none" stroke="#167866" stroke-width="2.5"/>${points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="3" fill="${p.experience===null?'#936015':'#167866'}"><title>${date(p.at)} JST / ${p.total.toFixed(3)} / ${e(p.kind)}</title></circle>`).join('')}<text x="55" y="216">${date(first.at)}</text><text x="670" y="216">${date(last.at)}</text></svg>`:'<p class="compact-empty">提督経験値を含む母港・基本情報の受信で記録を開始します。以前のデータから経験値を推測しません。</p>';
  return `<div class="toolbar"><label>集計期間<select id="score-month"><option value="all">全観測期間</option>${months.map(m=>`<option value="${m}" ${m===month?'selected':''}>${m} 作戦</option>`).join('')}</select></label><small>JST / 通常戦果は月末22時区切り / グラフは全保存履歴から集計</small></div><div class="score-stats"><div><small>観測通常戦果</small><strong>${s.normal.toFixed(3)}</strong></div><div><small>手動加算・訂正</small><strong>${s.bonus.toFixed(3)}</strong></div><div><small>記録済み合計</small><strong>${s.total.toFixed(3)}</strong></div><div><small>経験値観測点</small><strong>${s.observations}</strong></div></div>${panel('累積戦果の推移',plot+`<p class="page-note">最初の経験値を基準値とし、それ以降の増分を換算。ランキング表示の月次戦果そのものではありません。EO・任務・繰越は自動加算しません。${s.gaps?` <span class="warning">${s.gaps} 区間は経験値減少または月境界を跨ぐため加算せず再基準化しました。</span>`:''}</p>`)}<div class="layout">${panel('戦果の手動追記',`<form id="score-bonus-form"><div class="forms"><label>種類<select name="kind"><option>EO</option><option>任務</option><option>繰越</option><option>訂正</option></select></label><label>対象作戦月<input name="month" type="month" required value="${month==='all'?operationMonth(new Date().toISOString()):month}"></label><label>戦果値<input name="value" type="number" step="any" min="-100000" max="100000" required></label><label>根拠・訂正理由<input name="note" maxlength="200" required placeholder="任務名、報酬表示、元記録など"></label></div><button class="primary">記録を追記</button><p class="page-note">EO・任務は月末の締切が異なるため対象月を指定してください。誤記は「訂正」で負の値を追記します。重複入力に注意。</p></form>`)}${panel('経験値から計算',`<form id="score-calc-form"><label>増やす提督経験値<input name="xp" type="number" min="0" max="1000000000" step="1" value="10000" required></label><button>戦果に換算</button><output id="score-calc-result" class="calc-output">10,000 EXP = 7.000 戦果</output></form><p class="page-note">通常戦果 = 提督経験値増分 × 7 / 10,000。<a href="https://wikiwiki.jp/kancolle/%E7%A7%B0%E5%8F%B7%E3%83%BB%E6%88%A6%E6%9E%9C" target="_blank" rel="noreferrer">根拠: 攻略Wiki</a>（2026-09-07確認）</p>`)}</div>${panel('計算の内訳（直近50件）',`<div class="table-wrap"><table><thead><tr><th>日時 JST</th><th>種別 / 根拠</th><th>提督経験値</th><th>増分戦果</th><th>累積</th></tr></thead><tbody>${rows.slice(-50).reverse().map(r=>`<tr><td>${date(r.at)}</td><td>${e(r.kind)}${r.note?'<small>'+e(r.note)+'</small>':''}</td><td>${r.experience==null?'—':r.experience.toLocaleString()}</td><td>${r.delta.toFixed(3)}</td><td>${r.total.toFixed(3)}</td></tr>`).join('')}</tbody></table></div>`)}`;
}
